ページ作成
Fintan-contents/gai-dev-guide pull request #2
Opened 2024-11-07 01:29 UTC by takumontakumontakumontakumon

以下ページを作成

- GitHub Copilot導入に期待する効果
- インストール&設定 (所要時間5分〜10分)

2024-11-14 09:55 UTC, kiririmode commented
Copilot表記がありますが、プロダクト名なので正式名称としたいです。
Copilot表記を検知できるルールを追加したので、NGになっている箇所を修正いただきたいです。

0d0486e1d02e47eed3807c48715a26969b6d886a

2024-11-14 12:11 UTC, kiririmode requested changes

2024-11-14 12:11 UTC, kiririmode commented on website/docs/github-copilot/07_bestpractice/03_context.md
> +### ※1 コンテキストの提供
MUST: 

章タイトルに「※」が入るのは不自然です

2024-11-14 12:11 UTC, kiririmode commented on website/docs/github-copilot/07_bestpractice/03_context.md
> +- VS CodeでCopilotを使用している場合は、関連するファイルを開き、無関係なファイルを閉じます（※1）
ここでいうコンテキストの整理はなぜ必要なのか、GitHub Copilotがどういう仕組みで補完コードを作っているのかに触れつつ説明する文章がほしいです。
別指摘にも記述した通り、読者にとっての「突然」感が強いです。

2024-11-14 23:50 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot-current/01_projected-benefit/index.md
> +> GitHub Copilotを使用したグループのほうが、タスクの完了率が高かった(GitHub Copilotを使用しないグループの70%に対して、78%)。
引用元に合わせて箇条書きにしました
2f45f875ebcefc619e7216db611156ae035494b6

2024-11-14 23:51 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot-current/01_projected-benefit/index.md
> +> 実験では、両グループのタスク成功率の平均、および両グループが完了するまでに要した時間の平均を測定しました。
はい、情報量が少ないので削除しました
ecf802c8698c2f1e9dc8b2d432e94a0d5cd3b1f2

2024-11-14 23:51 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot-current/01_projected-benefit/index.md
> +> On average, within the first year in the market, users accept nearly 30% of code suggestions from GitHub Copilot
GitHubブログからの引用セクションは見直しました
ecf802c8698c2f1e9dc8b2d432e94a0d5cd3b1f2

2024-11-14 23:52 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/01_for-organization-admin/02_faq/index.md
> +「Suggestions+matching+public+code」という設定を「Blocked」にすることで。
上記いただいた修正内容を参考に修正しました
6c099726f513a2ee4a3b0c5d49402b26d6d198f5

2024-11-14 23:53 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/01_for-organization-admin/02_faq/index.md
> +### ライセンス関連のサポートについて
費用に持っていき、自然な文脈になるようにしました。
6c099726f513a2ee4a3b0c5d49402b26d6d198f5

2024-11-14 23:53 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/01_for-organization-admin/02_faq/index.md
> +# 導入検討時に考慮すべき事項 [FAQ]
そうですね。FAQにしました。
6c099726f513a2ee4a3b0c5d49402b26d6d198f5

2024-11-14 23:54 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/04_refactoring/index.md
> +![Untitled](images/Untitled.png)
このページ以外にも全ての画像のファイル名・キャプションを意味がわかる形に修正しました
a17f2e9af5d0d1282a9fb3742b359c5cb83ade7a

2024-11-14 23:54 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/04_refactoring/index.md
> +![スクリーンショット 2023-12-04 16.51.44.png](images/スクリーンショット_2023-12-04_16.51.44.png)
このページ以外にも全ての画像のファイル名・キャプションを意味がわかる形に修正しました
a17f2e9af5d0d1282a9fb3742b359c5cb83ade7a

2024-11-15 02:15 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/03_coding/index.md
> +セキュリティリスクの可能性があるか意見をもらう。
全ページにおいて、「文末。」「ですます/である調」を、本文と箇条書きごとに(ある程度)統一しました
cc5ae2c6894491e5bcdd88e731e7ce8b7594da48

2024-11-15 02:18 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/04_refactoring/index.md
> +        * 日付範囲のバリデーター。
修正しました
6a290d06e4b67254a59b39d24cad2cdd96e86912

2024-11-15 02:21 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/04_refactoring/index.md
> +- GitHub Copilot Chatにより、リファクタリング内容とリファクタリング後のクラスが提案されます
全ページにおいて、「文末。」「ですます/である調」を、本文と箇条書きごとに(ある程度)統一しました
cc5ae2c6894491e5bcdd88e731e7ce8b7594da48

一部の箇条書きは体現止めにしていますが、それ以外は以下ルールです
- 本文
  - 文末。つける
  - ですます調
 - 箇条書き
   - 文末。つけない
   - ですます調

2024-11-15 02:26 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/07_bestpractice/02_principles-for-effective-github-copilot-prompts.md
> +:::
他ページ含めて内容をリファクタリングすべき点ありますが、ひとまず引用を追加しました。
bc00d250ebc7fc2072b4ec5b2d32c95dc5d23459

2024-11-15 02:38 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/07_bestpractice/03_context.md
> +### ※1 コンテキストの提供
親セクション含めて自然な流れになるよう修正しました
9d8a939ba1487ad4f688e5659666c5ac85159bc2

2024-11-15 02:44 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/06_test/index.md
> +### 例１（提案時 → 提案受け入れ後）
これも「なぜそのタイミングでこの画像を読み手に見せているのか」という疑問はありますが、
ひとまず形式を修正しました。
疑問については別途対応します。

fbf9c89be3d9271f956973e7208bc8060fcc5040

2024-11-15 03:13 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/04_refactoring/index.md
> +        開発基準のMarkdownファイルを開発基準に、対象ファイルをレビューし、問題があれば、改修案を提示してください
修正しました
c0b6647c66b0952fc5494f37c79056621a9f1101
eabd2d006d5ef57a31df139d40cb4cf2df57968a

2024-11-15 03:16 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/05_code-analysis/index.md
> +「#file:CopyCallTreeAnalyzeTool.java ロジックを理解して、クラス図をMermaidで作成してください。
★TODO 別PullRequestにて対応★

2024-11-15 03:16 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/03_coding/index.md
> +
★TODO 別PullRequestにて対応★

2024-11-15 03:16 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/07_bestpractice/03_context.md
> +- 関数名fetchDataEndwithtxt（意味のある名前）
★TODO 別PullRequestにて対応★

2024-11-15 05:13 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/07_bestpractice/03_context.md
> +- VS CodeでCopilotを使用している場合は、関連するファイルを開き、無関係なファイルを閉じます（※1）
★TODO 別PullRequestにて対応★

2024-11-15 08:02 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/05_code-analysis/index.md
> +「#file:CopyCallTreeAnalyzeTool.java ロジックを理解して、クラス図をMermaidで作成してください。
https://github.com/Fintan-contents/gai-dev-guide/pull/4 にて 「コードを解析する」ページ修正しました。

2024-11-17 03:04 UTC, kiririmode-tis approved these changes

2024-11-17 03:05 UTC, merged

2024-11-18 07:00 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/03_coding/index.md
> +
https://github.com/Fintan-contents/gai-dev-guide/pull/4 で全ページに導入追記しました

2024-11-19 01:47 UTC, takumontakumontakumontakumon commented on website/docs/github-copilot/07_bestpractice/03_context.md
> +- 関数名fetchDataEndwithtxt（意味のある名前）
https://github.com/Fintan-contents/gai-dev-guide/pull/4 にて修正しました